CREATE TABLE "GCG_3782_COGS_Sales"(
 "Terminal" VARCHAR(3),
 "Order_Number" VARCHAR(7),
 "Order_Line" VARCHAR(4),
 "Invoice" VARCHAR(7),
 "Job" VARCHAR(6),
 "Suffix" VARCHAR(3),
 "Quantity" DOUBLE,
 "Sales_Stock" DOUBLE,
 "Sales_Special" DOUBLE,
 "Sales_Purchased" DOUBLE,
 "Cost_Stock" DOUBLE,
 "Cost_Special" DOUBLE,
 "Cost_Purchased" DOUBLE,
 "Cost_Blank" DOUBLE,
 "Special_Material" DOUBLE,
 "Special_Labor" DOUBLE,
 "Special_Overhead" DOUBLE,
 "Stock_Material" DOUBLE,
 "Stock_Labor" DOUBLE,
 "Stock_Overhead" DOUBLE,
 "Blank_Material" DOUBLE,
 "Blank_Labor" DOUBLE,
 "Blank_Overhead" DOUBLE,
 "Transaction_Date" DATE
);